### ISSUE TITLE
data saving

### ISSUE THREAD

**Issue by fanmingyu212** [Jayich-Lab/artiq#2]
There are several ways to save data with artiq experiments:
* use the built-in artiq experiment data saving. Relevant code: https://github.com/m-labs/artiq/blob/master/artiq/master/worker_db.py#L109, https://github.com/m-labs/artiq/blob/master/artiq/language/environment.py#L226
  - this only saves data to a file when an experiment finishes
  - this does not support save arbitrary attributes to the data (e.g., we might want to save trap parameters that is from a labrad server into the data files)
  - this organizes all data into a data directory organized by dates "date / run_number - experiment_name.h5". The run number increments with each experiment. For some monitoring data, we might want to save them in a folder structure like "experiment_name / data_number.h5".
* edit the artiq data saving functionalities. Functions we want include
  - save additional attributes
  - save a dataset in parts
  - save datasets that are not organized by the current data directory. They are typically monitoring datasets (temperature, PMT counts, pressure, etc.)
* have a separate labrad server to handle data saving
  - we won't have the nice data broadcasting provided by artiq, but we can implement our own using labrad signals.

We should discuss about these and maybe other options.

**Comment by fanmingyu212** [comment]
@gschaffner it would be great if you can update here about the speed comparison of csv and hdf5 file data saving.

**Comment by mczimmermann** [comment]
In the duke repo they have an example of how they save data as a numpy array:
https://gitlab.com/duke-artiq/dax-example/-/blob/master/programs/store_measurements.py

**Comment by fanmingyu212** [comment]
I think artiq.experiment.HasEnvironment base experiment also enables saving numpy arrays. I have not figured out how the dax example works and what the advantage of their method yet.
